FROM nginx:1.18.0
# RUN apt-get update && apt-get install -y -q vim
COPY --from=tsbase /code/ui/dist /app
COPY dhparam.pem /etc/nginx/
COPY services.conf /etc/nginx/
COPY nginx* /etc/nginx/
CMD ["/etc/nginx/nginxstart.sh"]
